import { Plus_Jakarta_Sans, Inter } from 'next/font/google';
import '@/styles/globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

// const inter = Inter({ subsets: ['latin'] });
const plusjakarta = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'in-folio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusjakarta.className}>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
